#!/usr/bin/env python3
"""Detect and materialize macOS cloud placeholders needed by pytest."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from collections.abc import Callable, Iterable
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Darwin's <sys/stat.h> calls this SF_DATALESS. Python does not currently expose
# the constant in ``stat``, but ``os.stat_result.st_flags`` carries the bit.
SF_DATALESS = 0x40000000


StatFunction = Callable[[Path], object]


def _may_materialize(path: Path) -> bool:
    """Exclude content-taboo environment files even if Git accidentally tracks one."""
    return path.name == ".env.example" or not path.name.startswith(".env")


def repository_candidate_files(root: Path = ROOT) -> list[Path]:
    """Return public Git candidates without opening content-taboo environment files."""
    completed = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        cwd=root,
        capture_output=True,
        check=False,
    )
    if completed.returncode:
        return []
    candidates = [
        root / value.decode("utf-8", errors="surrogateescape")
        for value in completed.stdout.split(b"\0")
        if value
    ]
    return [path for path in candidates if _may_materialize(path)]


def generated_public_bytecode_files(
    sources: Iterable[Path],
    *,
    cache_tag: str | None = sys.implementation.cache_tag,
) -> list[Path]:
    """Return current-runtime bytecode derived from candidate Python files."""
    if not cache_tag:
        return []
    stems_by_cache: dict[Path, set[str]] = {}
    for source in sources:
        if source.suffix == ".py":
            stems_by_cache.setdefault(source.parent / "__pycache__", set()).add(
                source.stem
            )

    bytecode: list[Path] = []
    for cache_dir, public_stems in stems_by_cache.items():
        try:
            for entry in cache_dir.iterdir():
                stem, separator, cache_suffix = entry.name.partition(".")
                if (
                    entry.suffix == ".pyc"
                    and separator
                    and stem in public_stems
                    and cache_suffix.startswith(cache_tag)
                ):
                    bytecode.append(entry)
        except (FileNotFoundError, NotADirectoryError, PermissionError):
            continue
    return sorted(bytecode)


def collection_input_files(root: Path = ROOT) -> list[Path]:
    """Return public candidates and only bytecode generated from their Python files."""
    candidates = repository_candidate_files(root)
    return [*candidates, *generated_public_bytecode_files(candidates)]


def find_dataless_files(
    paths: Iterable[Path],
    *,
    stat_function: StatFunction | None = None,
) -> list[Path]:
    """Find macOS dataless placeholders without opening their contents."""
    inspect_path = stat_function or os.lstat
    dataless: list[Path] = []
    for path in paths:
        try:
            flags = getattr(inspect_path(path), "st_flags", 0)
        except (FileNotFoundError, PermissionError):
            continue
        if flags & SF_DATALESS:
            dataless.append(path)
    return dataless


def _materialize_file(path: Path) -> None:
    try:
        with path.open("rb") as source:
            while source.read(1024 * 1024):
                pass
    except OSError:
        pass


def materialize_files(paths: Iterable[Path], *, workers: int = 16) -> None:
    """Force local materialization with bounded parallel reads."""
    with ThreadPoolExecutor(max_workers=workers) as executor:
        list(executor.map(_materialize_file, paths))


def format_pytest_error(paths: list[Path], root: Path = ROOT) -> str:
    """Build a bounded, clone-portable explanation for pytest startup."""
    samples = "\n".join(
        f"  - {path.relative_to(root).as_posix()}" for path in paths[:5]
    )
    remainder = f"\n  - ... and {len(paths) - 5} more" if len(paths) > 5 else ""
    return (
        f"pytest cannot start reliably: macOS offloaded {len(paths)} repository "
        "file(s).\n"
        f"{samples}{remainder}\n"
        "Run `poetry run python scripts/check_macos_cloud_files.py --hydrate`, "
        "then mark the repository Keep Downloaded in Finder to prevent recurrence."
    )


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check pytest inputs for macOS dataless placeholders."
    )
    parser.add_argument(
        "--hydrate",
        action="store_true",
        help="read public files and their generated bytecode, forcing materialization",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if sys.platform != "darwin":
        print("macOS cloud-file check skipped on this platform")
        return 0

    inputs = collection_input_files()
    dataless = find_dataless_files(inputs)
    if args.hydrate and dataless:
        print(
            f"Materializing {len(dataless)} public repository file(s)...",
            flush=True,
        )
        materialize_files(dataless)
        dataless = find_dataless_files(inputs)

    if dataless:
        print(format_pytest_error(dataless), file=sys.stderr)
        return 1

    print("All public repository files are available locally")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
